export default {
    FETCH_DATA: 'FETCH_DATA',
    GOT_DATA: 'GOT_DATA',
    GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
    GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
    CLEAR_PRODUCT_DETAILS: 'CLEAR_PRODUCT_DETAILS',
    ADD_ITEMS_TO_CART:'ADD_ITEMS_TO_CART',
    GET_ACTIVE_CART: 'GET_ACTIVE_CART'
}